<x-layouts.admin :title="__('admin.user_details')">
<div class="admin-heading-row"><div><h2>{{ $managedUser->name }}</h2><p class="admin-lead"><bdi>{{ $managedUser->email }}</bdi> · <bdi>{{ $managedUser->username }}</bdi></p></div>@can('update',$managedUser)<a class="admin-button admin-button-secondary" href="{{ route('admin.users.edit',$managedUser) }}">{{ __('admin.edit_user') }}</a>@endcan</div>
<dl class="admin-details"><div><dt>{{ __('admin.status') }}</dt><dd><span class="admin-badge status-{{ $managedUser->status->value }}">{{ __('admin.statuses.'.$managedUser->status->value) }}</span></dd></div><div><dt>{{ __('admin.verification') }}</dt><dd>{{ $managedUser->hasVerifiedEmail()?__('admin.verified'):__('admin.not_verified') }}</dd></div><div><dt>{{ __('admin.phone') }}</dt><dd><bdi>{{ $managedUser->phone_e164 ?: '—' }}</bdi></dd></div><div><dt>{{ __('admin.created') }}</dt><dd>{{ $managedUser->created_at->locale(app()->getLocale())->translatedFormat('Y M j, H:i') }}</dd></div></dl>

<section class="admin-section"><h2>{{ __('admin.assign_roles') }}</h2>
@can('assignRoles',$managedUser)<form method="POST" action="{{ route('admin.users.roles',$managedUser) }}" class="admin-form">@csrf @method('PUT')<div class="admin-check-grid">@foreach($assignableRoles as $role)<label><input type="checkbox" name="roles[]" value="{{ $role->id }}" @checked($managedUser->roles->contains('id',$role->id))><span>{{ __('admin.role_names.'.$role->name) !== 'admin.role_names.'.$role->name ? __('admin.role_names.'.$role->name) : $role->name }}</span></label>@endforeach</div><button class="admin-button" type="submit">{{ __('admin.save_roles') }}</button></form>
@else<p class="admin-muted">{{ $managedUser->roles->pluck('name')->join('، ') ?: __('admin.no_roles_assigned') }}</p>@endcan
</section>

@can('changeStatus',$managedUser)<section class="admin-section"><h2>{{ __('admin.account_access') }}</h2><form method="POST" action="{{ route('admin.users.status',$managedUser) }}" class="admin-inline-form">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $managedUser->status->value==='active'?'disabled':'active' }}"><label>{{ __('admin.status_reason') }}<input name="reason" required minlength="8" maxlength="200"><small>{{ __('admin.reason_hint') }}</small></label><button @class(['admin-button','admin-button-danger'=>$managedUser->status->value==='active']) type="submit">{{ $managedUser->status->value==='active'?__('admin.disable'):__('admin.reactivate') }}</button></form></section>@endcan

@can('delete',$managedUser)<section class="admin-section admin-danger-zone"><h2>{{ __('admin.delete') }}</h2><form method="POST" action="{{ route('admin.users.destroy',$managedUser) }}" onsubmit="return confirm(@js(__('admin.delete_confirm')))" >@csrf @method('DELETE')<button class="admin-button admin-button-danger" type="submit">{{ __('admin.delete') }}</button></form></section>@endcan
</x-layouts.admin>
