<x-layouts.admin :title="__('prompts.admin_title')">
<div class="admin-heading-row"><p class="admin-lead">{{ __('prompts.admin_intro') }}</p><a class="admin-button" href="{{ route('admin.prompts.create') }}">{{ __('prompts.create') }}</a></div>
<form method="GET" class="admin-filters prompt-admin-filters">
<label>{{ __('prompts.search') }}<input name="search" value="{{ $filters['search']??'' }}" maxlength="100" placeholder="{{ __('prompts.search_placeholder') }}"></label>
<label>{{ __('prompts.status') }}<select name="status"><option value="">{{ __('prompts.all_statuses') }}</option>@foreach(['draft','published','archived'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ __('prompts.statuses.'.$status) }}</option>@endforeach</select></label>
<label>{{ __('prompts.category') }}<select name="category"><option value="">{{ __('prompts.all_categories') }}</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string)($filters['category']??'')===(string)$category->id)>{{ $category->localizedName() }}</option>@endforeach</select></label>
<div class="admin-filter-actions"><button class="admin-button">{{ __('prompts.filter') }}</button><a href="{{ route('admin.prompts.index') }}">{{ __('prompts.clear') }}</a></div></form>
<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>{{ __('prompts.title') }}</th><th>{{ __('prompts.status') }}</th><th>{{ __('prompts.visibility') }}</th><th>{{ __('prompts.category') }}</th><th>{{ __('prompts.uses') }}</th><th>{{ __('prompts.actions') }}</th></tr></thead><tbody>
@forelse($prompts as $prompt)<tr><td data-label="{{ __('prompts.title') }}"><strong>{{ $prompt->title }}</strong><small><bdi>{{ $prompt->slug }}</bdi></small></td><td data-label="{{ __('prompts.status') }}"><span class="admin-badge status-{{ $prompt->status->value==='published'?'active':'disabled' }}">{{ __('prompts.statuses.'.$prompt->status->value) }}</span></td><td data-label="{{ __('prompts.visibility') }}">{{ __('prompts.visibilities.'.$prompt->visibility->value) }}</td><td data-label="{{ __('prompts.category') }}">{{ $prompt->category?->localizedName() ?? __('prompts.no_category') }}</td><td data-label="{{ __('prompts.uses') }}">{{ $prompt->uses_count }}</td><td data-label="{{ __('prompts.actions') }}"><div class="category-actions"><a href="{{ route('admin.prompts.show',$prompt) }}">{{ __('prompts.preview') }}</a><a href="{{ route('admin.prompts.edit',$prompt) }}">{{ __('prompts.edit') }}</a></div></td></tr>@empty<tr><td colspan="6" class="admin-empty">{{ __('prompts.none_admin') }}</td></tr>@endforelse
</tbody></table></div><div class="admin-pagination">{{ $prompts->links() }}</div>
</x-layouts.admin>
