<x-layouts.portal :title="$conversation->title">
<div class="ai-workspace">
<aside class="ai-history-sidebar" aria-label="{{ __('ai.history') }}"><a class="admin-button" href="{{ route('ai.create') }}">{{ __('ai.new') }}</a><a class="prompt-back" href="{{ route('ai.index') }}">{{ __('ai.view_all_history') }}</a><nav>@foreach($recentConversations as $recent)<a @class(['is-current'=>$recent->is($conversation)]) href="{{ route('ai.show',$recent) }}"><span>{{ $recent->title }}</span><time>{{ ($recent->last_message_at ?? $recent->created_at)->locale(app()->getLocale())->diffForHumans() }}</time></a>@endforeach</nav></aside>
<div class="ai-chat-panel">
<div class="ai-chat-heading"><a class="prompt-back" href="{{ route('ai.index') }}">← {{ __('ai.back') }}</a><div class="ai-chat-controls"><form method="POST" action="{{ route('ai.rename',$conversation) }}">@csrf @method('PATCH')<label class="sr-only" for="conversation-title">{{ __('ai.conversation_title') }}</label><input id="conversation-title" name="title" value="{{ $conversation->title }}" maxlength="160" required><button>{{ __('ai.rename') }}</button></form><form method="POST" action="{{ route('ai.archive',$conversation) }}">@csrf @method('PATCH')<input type="hidden" name="archived" value="{{ $conversation->archived_at ? 0 : 1 }}"><button>{{ $conversation->archived_at ? __('ai.restore') : __('ai.archive') }}</button></form><form method="POST" action="{{ route('ai.destroy',$conversation) }}" onsubmit="return confirm(@js(__('ai.delete_confirm')))">@csrf @method('DELETE')<button class="prompt-danger-button">{{ __('ai.delete') }}</button></form></div></div>
@if($messages->hasMorePages())<a class="ai-older-link" href="{{ $messages->nextPageUrl() }}">{{ __('ai.older_messages') }}</a>@endif
<section class="ai-thread" aria-live="polite">@foreach($messages as $message)<article @class(['ai-message','is-user'=>$message->role==='user','is-assistant'=>$message->role==='assistant'])><strong>{{ $message->role==='user' ? auth()->user()->name : __('ai.title') }}</strong><div>{!! nl2br(e($message->content)) !!}</div><footer>@if($message->model)<span dir="ltr">{{ $message->model }}</span>@endif<time datetime="{{ $message->created_at->toAtomString() }}">{{ $message->created_at->locale(app()->getLocale())->diffForHumans() }}</time>@if($message->role==='assistant' && $message->total_tokens)<span>{{ $message->total_tokens }} tokens</span>@endif</footer></article>@if($message->role==='user')@php($aiRequest=$conversation->requests->firstWhere('user_message_id',$message->id))@if($aiRequest && in_array($aiRequest->status,[\App\Enums\AiRequestStatus::Queued,\App\Enums\AiRequestStatus::Processing]))<div class="ai-request-state" data-ai-poll="{{ route('ai.status',[$conversation,$aiRequest]) }}"><span class="ai-spinner"></span>{{ __('ai.processing') }}<form method="POST" action="{{ route('ai.cancel',[$conversation,$aiRequest]) }}">@csrf<button>{{ __('ai.cancel') }}</button></form></div>@elseif($aiRequest && $aiRequest->status===\App\Enums\AiRequestStatus::Failed)<div class="ai-request-state is-error">{{ __('ai.errors.'.$aiRequest->failure_code) }}<form method="POST" action="{{ route('ai.retry',[$conversation,$aiRequest]) }}">@csrf<button>{{ __('ai.retry') }}</button></form></div>@elseif($aiRequest && $aiRequest->status===\App\Enums\AiRequestStatus::Cancelled)<div class="ai-request-state">{{ __('ai.cancelled') }}</div>@endif @endif @endforeach</section>
@if($messages->currentPage()>1)<a class="ai-older-link" href="{{ route('ai.show',$conversation) }}">{{ __('ai.latest_messages') }}</a>@endif
<form method="POST" action="{{ route('ai.send',$conversation) }}" class="ai-compose ai-compose-inline">@csrf<input type="hidden" name="client_operation_id" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><label>{{ __('ai.model') }}<select name="model" dir="ltr">@foreach($models as $model)<option value="{{ $model }}" @selected($model===$conversation->model)>{{ $model }}</option>@endforeach</select></label><label>{{ __('ai.continue') }}<textarea name="content" maxlength="20000" required placeholder="{{ __('ai.message_placeholder') }}"></textarea></label><button class="admin-button">{{ __('ai.send') }}</button></form>
</div></div>
</x-layouts.portal>
